# Default values for observatory-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: starwitorg/observatory-config
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

nameOverride: ""
fullnameOverride: "observatory-config"

app:
  contextPath: ""
  observatoryUrl: ""

auth:
  enabled: true
  keycloakRealmUrlInternal: http://internal-hostname/realms/observatory-config
  keycloakRealmUrlExternal: https://external-hostname/realms/observatory-config
  clientId: observatory-config
  clientSecret: observatory-config # TODO get from secret

database:
  internal: true
  name: observatory-config
  username: observatory-config
  password: observatory-config

# extraEnv: |
#   - name: JAVA_TOOL_OPTIONS
#     value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000
#   - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
#     value: INFO
#   - name: LOGGING_LEVEL_ROOT
#     value: DEBUG

ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: spc.data-wolfsburg.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: spc.data-wolfsburg.de
      hosts:
        - spc.data-wolfsburg.de

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    memory: "1000Mi"
