CREATE TABLE "detection" (
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "stream_id"           VARCHAR(255) NOT NULL,
    "object_id"           VARCHAR(255) NOT NULL,
    "class_id"            INTEGER      NOT NULL,
    "detection_timestamp" TIMESTAMP    NOT NULL,
    "latitude"            DOUBLE PRECISION,
    "longitude"           DOUBLE PRECISION,
    "x"                   DOUBLE PRECISION,
    "y"                   DOUBLE PRECISION
);
