name: PR Build

# PR build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


# just runs Maven, NPM and Docker build
jobs:
  build:
    name: "Install software"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2        

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - run: npm --version
    - run: node --version
    - run: mvn --version

    - name: npm install
      run: |
        if [ -d "webclient/app" ]; then
          cd webclient/app
          npm install
        fi

    - name: Build with Maven
      run: mvn clean -B package -P frontend --file pom.xml
      env:
         CI: false

  checks:
    name: "Checks"
    needs: build
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: get helm
      uses: azure/setup-helm@v4

    - name: run helm dependency update
      working-directory: application/target/helm/observatory-config
      run: helm dep update

    - name: run helm template
      working-directory: application/target/helm
      run: helm template observatory-config

